name: Generate and Commit PHP Documentation

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  generate_docs:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate PHP Documentation
        run: phpdoc
        
      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs
          git commit -m "Update PHP documentation [skip ci]"
          git push
